import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'ar'; // Default to Arabic
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.catalog': 'Data Catalog',
    'nav.genomics': 'Genomics Hub',
    'nav.research': 'Research & Community',
    'nav.contact': 'Contact',
    'nav.submit': 'Submit Data',
    'nav.centers': 'Seed Stations',
    'nav.inventory': 'Seed Bank',
    'nav.aiPrediction': 'AI Prediction',
    'nav.publicAccess': 'Public Access',

    // Header
    'header.title': 'Seed Center Data Hub',
    'header.subtitle': 'Ministry of Environment, Water & Agriculture',

    // Home Page
    'home.hero.title': 'MEWA Seed & Seedlings Data Center',
    'home.hero.description': 'Passport data for 8 crops across nine Saudi regions. Filter by crop, region, and accession details.',
    'home.hero.subtitle': 'Ministry of Environment, Water & Agriculture',
    'home.stats.total': 'Total Samples',
    'home.stats.totalDesc': 'Across all regions',
    'home.stats.wheat': 'Wheat Accessions',
    'home.stats.wheatDesc': 'Triticum species',
    'home.stats.coffee': 'Coffee Accessions',
    'home.stats.coffeeDesc': 'Coffea arabica',
    'home.map.title': 'Regional Distribution',
    'home.map.description': 'Interactive map showing seed collection sites across Saudi Arabia',
    'home.catalog.title': 'Data Catalog',
    'home.catalog.description': 'Browse complete seed passport database',

    // Home badges & labels
    'home.badge.totalAccessions': 'Total Accessions',
    'home.badge.cropsWithData': 'Crops with Passport Data',
    'home.badge.saudiRegions': 'Saudi Regions',
    'home.label.accessions': 'accessions',
    'home.label.activeRegions': 'Active regions',
    'home.label.saudiAccessions': 'Saudi accessions',
    'home.label.filteringBy': 'Filtering by:',
    'home.label.clearAll': 'Clear all',
    'home.label.showingSaudi': 'Showing {n} Saudi accessions',
    'home.label.clickRegion': 'Click a region marker to highlight it. Click crop tiles above to filter.',
    'home.label.domCropColor': '(Marker color = dominant crop in region)',
    'home.label.passportSummary': 'Passport Data Summary',
    'home.label.clickToExplore': 'Click a region on the map or a crop tile to explore',
    'home.label.totalAccessions': 'Total accessions',
    'home.label.saudiCount': 'Saudi',
    'home.label.noteMappedRegions': 'Saudi accessions from this region with passport data. International accessions (CIMMYT, ICARDA, etc.) are not shown geographically.',
    'home.label.regionBreakdown': 'Region Breakdown',
    'home.kpi.totalAccessions': 'Total Accessions',
    'home.kpi.cropsTracked': 'Crops Tracked',
    'home.kpi.saudiRegions': 'Saudi Regions',
    'home.kpi.genomicData': 'Genomic Data',
    'home.kpi.tbData': 'TB',
    'home.chart.cropDistribution': 'Crop Distribution',
    'home.chart.cropDistributionDesc': 'Accessions by crop type',
    'home.chart.regionalOverview': 'Regional Overview',
    'home.chart.regionalOverviewDesc': 'Saudi accessions per region',
    'home.chart.sequencingBreakdown': 'Sequencing Coverage',
    'home.chart.sequencingDesc': 'GBS vs WGS across crops',
    'home.chart.saudiVsIntl': 'Saudi vs International',
    'home.chart.saudiVsIntlDesc': 'Origin breakdown per crop',
    'home.section.exploreData': 'Explore the Data',
    'home.section.exploreDataDesc': 'Comprehensive view of genomic and seed passport data distribution across Saudi Arabia',
    'home.label.saudi': 'Saudi',
    'home.label.international': 'International',
    'home.label.gbs': 'GBS',
    'home.label.wgs': 'WGS',

    // Submit Data Page
    'submit.tab': 'Submit Data',
    'submit.badge.new': 'Data Submission Portal',
    'submit.hero.title': 'Submit Genomic & Passport Data',
    'submit.hero.description': 'Upload your sequencing data and seed passport records. Receive a DataCite DOI for your dataset to cite in publications.',
    'submit.step.researcher.title': 'Researcher Information',
    'submit.step.researcher.desc': 'Tell us about yourself and your institution',
    'submit.step.passport.title': 'Seed Passport Data',
    'submit.step.passport.desc': 'Enter accession and collection details',
    'submit.step.genomic.title': 'Genomic Data',
    'submit.step.genomic.desc': 'Describe your sequencing data and upload files',
    'submit.step.doi.title': 'DOI Assignment',
    'submit.step.doi.desc': 'Review your DataCite DOI and metadata',
    'submit.step.confirm.title': 'Confirmation',
    'submit.step.confirm.desc': 'Your submission is complete',
    'submit.field.fullName': 'Full Name',
    'submit.field.institution': 'Institution',
    'submit.field.department': 'Department',
    'submit.field.email': 'Email Address',
    'submit.field.orcid': 'ORCID iD',
    'submit.hint.orcid': 'Your ORCID researcher identifier (optional)',
    'submit.field.crop': 'Crop Species',
    'submit.field.accessionId': 'Accession ID',
    'submit.field.region': 'Collection Region',
    'submit.field.collectionDate': 'Collection Date',
    'submit.field.collectorName': 'Collector Name',
    'submit.field.siteDescription': 'Site Description',
    'submit.field.latitude': 'Latitude',
    'submit.field.longitude': 'Longitude',
    'submit.field.altitude': 'Altitude',
    'submit.placeholder.selectCrop': 'Select a crop...',
    'submit.placeholder.selectRegion': 'Select a region...',
    'submit.field.sequencingType': 'Sequencing Type',
    'submit.field.platform': 'Sequencing Platform',
    'submit.field.coverageDepth': 'Coverage Depth',
    'submit.field.fileTypes': 'File Types',
    'submit.hint.fileTypes': 'Select all file types included in your submission',
    'submit.field.uploadFiles': 'Upload Files',
    'submit.upload.dragDrop': 'Drag & drop files here, or click to browse',
    'submit.upload.maxSize': 'Max 50 GB per submission. FASTQ, BAM, VCF, PLINK supported.',
    'submit.field.sraAccession': 'SRA/ENA Accession (if available)',
    'submit.field.dataDescription': 'Dataset Description',
    'submit.placeholder.selectPlatform': 'Select sequencing platform...',
    'submit.doi.title': 'Your DataCite DOI',
    'submit.doi.description': 'A unique Digital Object Identifier has been assigned to your dataset',
    'submit.doi.copyLink': 'Copy DOI link',
    'submit.doi.copied': 'Copied!',
    'submit.doi.resolvesTo': 'Resolves to:',
    'submit.doi.metadataPreview': 'DataCite Metadata',
    'submit.confirm.title': 'Submission Complete!',
    'submit.confirm.description': 'Your genomic data and passport records have been submitted for review. You will receive a confirmation email once your dataset is published.',
    'submit.confirm.reviewNote': 'Submissions are typically reviewed within 3-5 business days.',
    'submit.nav.back': 'Back',
    'submit.nav.next': 'Continue',
    'submit.nav.mintDoi': 'Mint DOI & Submit',
    'submit.nav.submitAnother': 'Submit Another Dataset',

    // Data Catalog
    'catalog.title': 'Data Catalog',
    'catalog.description': 'Browse, search, and export comprehensive seed passport data from MEWA collections',
    'catalog.totalRecords': 'Total Records',
    'catalog.allAccessions': 'All accessions',
    'catalog.wheat': 'Wheat',
    'catalog.triticum': 'Triticum accessions',
    'catalog.coffee': 'Coffee',
    'catalog.coffea': 'Coffea accessions',
    'catalog.exportData': 'Export Data',
    'catalog.fingerprints': 'Genetic Fingerprint Database',
    'catalog.fingerprintsDesc': 'Access molecular markers, DNA barcodes, and genetic fingerprints for all accessions',
    'catalog.viewFingerprints': 'View Fingerprints',
    'catalog.filters': 'Filters',
    'catalog.search': 'Search',
    'catalog.searchPlaceholder': 'Accession ID, location...',
    'catalog.cropType': 'Crop Type',
    'catalog.regions': 'Saudi Regions',
    'catalog.showing': 'Showing',
    'catalog.of': 'of',
    'catalog.samples': 'samples',
    'catalog.exportCSV': 'Export CSV',
    'catalog.accessionId': 'Accession ID',
    'catalog.crop': 'Crop',
    'catalog.arabicName': 'Arabic Name',
    'catalog.scientificName': 'Scientific Name',
    'catalog.country': 'Country',
    'catalog.region': 'Region',
    'catalog.location': 'Location',

    // Genetic Fingerprints
    'fingerprints.title': 'Genetic Fingerprints',
    'fingerprints.description': 'Comprehensive molecular marker profiles and DNA barcodes for all MEWA seed accessions',
    'fingerprints.totalFingerprints': 'Total Fingerprints',
    'fingerprints.completeProfiles': 'Complete profiles',
    'fingerprints.ssrMarkers': 'SSR Markers',
    'fingerprints.acrossAccessions': 'Across all accessions',
    'fingerprints.dnaBarcodes': 'DNA Barcodes',
    'fingerprints.uniqueIdentifiers': 'Unique identifiers',
    'fingerprints.genotypedLoci': 'Genotyped Loci',
    'fingerprints.perAccession': 'Per accession',
    'fingerprints.searchTitle': 'Search Genetic Fingerprints',
    'fingerprints.searchDesc': 'Find molecular marker profiles by accession ID or local name',
    'fingerprints.searchPlaceholder': 'Search by accession ID or name...',
    'fingerprints.all': 'All',
    'fingerprints.database': 'Fingerprint Database',
    'fingerprints.accessions': 'accessions',
    'fingerprints.export': 'Export',
    'fingerprints.dnaBarcode': 'DNA Barcode',
    'fingerprints.ssrProfile': 'SSR Profile',
    'fingerprints.geneticBarcode': 'Genetic Barcode',
    'fingerprints.ssrMarkerProfile': 'SSR Marker Profile',
    'fingerprints.showingOf': 'Showing',
    'fingerprints.loadMore': 'Load More',
    'fingerprints.noResults': 'No fingerprints found',
    'fingerprints.noResultsDesc': 'Try adjusting your search criteria or filters',

    // Genomics Hub
    'genomics.title': 'Genomics Hub',
    'genomics.description': 'Access genetic sequences, molecular markers, and bioinformatics tools',

    // Seed Stations (merged Centers + Exchange)
    'st.hero.badge': 'Seed Stations & Exchange',
    'st.hero.title': 'Seed Stations Across the Kingdom',
    'st.hero.subtitle': 'Explore seed centers, request germplasm samples, and track your seed exchange requests — all in one place',
    'st.kpi.stations': 'Stations',
    'st.kpi.staff': 'Staff',
    'st.kpi.experiments': 'تجارب / Experiments',
    'st.kpi.distributed': 'kg Distributed',
    'st.tab.map': 'Map View',
    'st.tab.list': 'List View',
    'st.tab.charts': 'Station Charts',
    'st.tab.seeds': 'Available Seeds',
    'st.tab.process': 'Request Process',
    'st.tab.guidelines': 'Guidelines',
    'st.filter.region': 'Region',
    'st.filter.allRegions': 'All Regions',
    'st.filter.crop': 'Crop',
    'st.filter.allCrops': 'All Crops',
    'st.list.staff': 'staff',
    'st.list.experiments': 'experiments',
    'st.list.hortVarieties': 'Hort. Varieties',
    'st.seeds.requestTitle': 'Request Seeds',
    'st.seeds.requestDesc': 'Submit a new seed request for research',
    'st.seeds.newRequest': 'New Request',
    'st.seeds.browseTitle': 'Browse Catalog',
    'st.seeds.browseDesc': 'Explore available seed accessions',
    'st.seeds.viewCatalog': 'View Catalog',
    'st.seeds.trackTitle': 'Track Requests',
    'st.seeds.trackDesc': 'Monitor your request status',
    'st.seeds.myRequests': 'My Requests',
    'st.seeds.featuredTitle': 'Featured Seed Collections',
    'st.seeds.featuredDesc': 'High-demand accessions available for immediate request',
    'st.seeds.available': 'Available',
    'st.seeds.limited': 'Limited',
    'st.seeds.accession': 'Accession',
    'st.seeds.qty': 'Available',
    'st.seeds.requestSample': 'Request Sample',
    'st.process.workflowTitle': 'Seed Request Workflow',
    'st.process.workflowDesc': 'Step-by-step process for requesting seed samples from MEWA Seed Center',
    'st.process.step': 'Step',
    'st.process.current': 'Current',
    'st.step1.title': 'Submit Request',
    'st.step1.desc': 'Complete the online request form with research details and required accessions',
    'st.step2.title': 'Review & Approval',
    'st.step2.desc': 'MEWA team reviews your request and research justification (2-5 business days)',
    'st.step3.title': 'MTA Agreement',
    'st.step3.desc': 'Sign Material Transfer Agreement outlining terms of use and data sharing',
    'st.step4.title': 'Seed Preparation',
    'st.step4.desc': 'Seeds are prepared, packaged, and quality-checked for shipment',
    'st.step5.title': 'Shipment',
    'st.step5.desc': 'Seeds are shipped to your institution with tracking information',
    'st.process.statusTitle': 'Sample Request Status',
    'st.process.statusDesc': 'Track your recent seed requests',
    'st.process.viewDetails': 'View Details',
    'st.guide.eligTitle': 'Eligibility Requirements',
    'st.guide.elig1': 'Research Institutions: Universities, research centers, and government agencies conducting agricultural research',
    'st.guide.elig2': 'Breeding Programs: Registered plant breeding organizations with documented programs',
    'st.guide.elig3': 'Conservation Projects: Approved conservation and biodiversity initiatives',
    'st.guide.elig4': 'Educational Use: Academic institutions for teaching and student research projects',
    'st.guide.docsTitle': 'Required Documentation',
    'st.guide.doc1': 'Research Proposal: Detailed description of research objectives and methodology',
    'st.guide.doc2': 'Institutional Letter: Official letter from your organization supporting the request',
    'st.guide.doc3': 'MTA Signature: Signed Material Transfer Agreement acknowledging terms and conditions',
    'st.guide.doc4': 'Import Permits: Required phytosanitary certificates for international requests',
    'st.guide.termsTitle': 'Terms of Use',
    'st.guide.termsIntro': 'Seeds provided by MEWA Seed Center are for research and breeding purposes only. Recipients must:',
    'st.guide.term1': 'Use seeds only for stated research objectives',
    'st.guide.term2': 'Not distribute seeds to third parties without permission',
    'st.guide.term3': 'Acknowledge MEWA in publications using the germplasm',
    'st.guide.term4': 'Share research results and data as outlined in MTA',
    'st.guide.term5': 'Comply with Nagoya Protocol and national regulations',
    'st.guide.contactTitle': 'Contact Information',
    'st.guide.coordinator': 'Seed Exchange Coordinator',
    'st.guide.email': 'Email',
    'st.guide.phone': 'Phone',
    'st.guide.hours': 'Office Hours',
    'st.guide.hoursVal': 'Sunday - Thursday, 8:00 AM - 4:00 PM',
    'st.dialog.area': 'Area',
    'st.dialog.totalArea': 'Total Area',
    'st.dialog.utilizedArea': 'Utilized Area',
    'st.dialog.staff': 'Staff',
    'st.dialog.equipment': 'Equipment',
    'st.dialog.needs': 'Needs',
    'st.dialog.visits': 'Visits',
    'st.dialog.manager': 'Manager',
    'st.dialog.noContact': 'No contact details available',
    'st.dialog.crops': 'Crops',
    'st.dialog.est': 'Est.',
    'st.dialog.experiments': 'تجارب زراعية / Experiments',
    'st.dialog.cropsPlanted': 'Crops Planted',
    'st.dialog.varieties': 'varieties',
    'st.dialog.activities': 'Activities',
    'st.dialog.seedExchange': 'Seed Exchange',
    'st.dialog.distYear': 'kg Distributed/year',
    'st.dialog.recYear': 'kg Received/year',
    'st.dialog.partners': 'Partners',
    'st.dialog.contact': 'Contact Information',

    // Research & Community (merged)
    'research.title': 'Research & Community',
    'research.description': 'Publications, projects, researchers, and institutions',
    'rc.hero.badge': 'Research & Community Hub',
    'rc.hero.title': 'Saudi Agricultural Research & Scientific Community',
    'rc.hero.subtitle': '22 comprehensive studies (2009–2025), 127 researchers, and 42 partner institutions advancing crop genomics across the Kingdom',
    'rc.kpi.studies': 'Studies',
    'rc.kpi.studiesSub': '2009–2025',
    'rc.kpi.researchers': 'Researchers',
    'rc.kpi.researchersSub': 'Active members',
    'rc.kpi.institutions': 'Institutions',
    'rc.kpi.institutionsSub': 'Partner organizations',
    'rc.kpi.countries': 'Countries',
    'rc.kpi.countriesSub': 'Global reach',
    'rc.kpi.collaborations': 'Collaborations',
    'rc.kpi.collaborationsSub': 'Joint projects',
    'rc.kpi.markers': 'Marker Types',
    'rc.kpi.markersSub': 'ISSR, SSR, SCoT, CRISPR…',
    'rc.tab.saudi': 'Saudi Direct',
    'rc.tab.regional': 'Regional',
    'rc.tab.drought': 'Drought Studies',
    'rc.tab.vegetables': 'Vegetables',
    'rc.tab.gaps': 'Gaps & Recs',
    'rc.tab.seedcenter': 'Seed Center Research',
    'rc.tab.researchers': 'Researchers',
    'rc.tab.institutions': 'Institutions',
    'rc.markers': 'Markers',
    'rc.saudi.heading': 'Primary Saudi Arabia Direct Studies',
    'rc.saudi.sub': '4 studies conducted directly in KSA',
    'rc.regional.heading': 'Regional Studies Applicable to Saudi Arabia',
    'rc.regional.sub': '7 studies from MENA region with direct KSA relevance',
    'rc.drought.heading': 'Wheat Drought Tolerance & Stress Studies',
    'rc.drought.sub': '5 studies — multiple marker types, direct Saudi applications',
    'rc.drought.markerTitle': 'Most Frequent Molecular Markers',
    'rc.veg.heading': 'Saudi Vegetable & Landrace Studies',
    'rc.veg.sub': '3 studies — genetic diversity preservation and breeding',
    'rc.seed.heading': 'Food Security & Seed Banking Studies',
    'rc.seed.sub': '3 studies — seed conservation and arid-region food security',
    'rc.gaps.gapsTitle': 'Research Gaps in Saudi Agriculture',
    'rc.gaps.partnersTitle': 'Partner Institutions',
    'rc.gaps.recsTitle': 'Recommendations for Saudi Agricultural Genomics',
    'rc.researchers.heading': 'Featured Researchers',
    'rc.researchers.sub': 'Scientists and breeders working with MEWA germplasm resources',
    'rc.researchers.contact': 'Contact',
    'rc.researchers.expertise': 'Research Expertise',
    'rc.researchers.projects': 'Projects',
    'rc.researchers.publications': 'Publications',
    'rc.institutions.heading': 'Partner Institutions',
    'rc.institutions.sub': 'Universities and research organizations collaborating with MEWA',
    'rc.institutions.researchers': 'researchers',
    'rc.institutions.projects': 'projects',

    // Contact
    'contact.title': 'Contact Us',
    'contact.description': 'Get in touch with MEWA Seed Center',

    // About
    'about.title': 'About MEWA Seed Center',
    'about.description': 'Our mission and vision',

    // Footer
    'footer.title': 'MEWA Seed Center',
    'footer.subtitle': 'Ministry of Environment, Water & Agriculture',
    'footer.country': 'Kingdom of Saudi Arabia',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.email': 'Email: nalsofuani@mewa.gov.sa',
    'footer.phone': 'Phone: +966 50 018 3515',
    'footer.contactForm': 'Contact Form',
    'footer.rights': '© 2026 Ministry of Environment, Water & Agriculture. All rights reserved.',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.reset': 'Reset',
    'common.apply': 'Apply',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.first': 'First',
    'common.last': 'Last',
    'common.page': 'Page',
    'common.perPage': 'per page',
    'common.total': 'Total',
    'common.selected': 'selected',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.crops': 'Crops',
    'common.staff': 'Staff',
    'common.employees': 'employees',
    'common.centers': 'Centers',
    'common.viewDetails': 'View Details',

    // Regions
    'region.taif': 'Taif',
    'region.aseer': 'Aseer',
    'region.albaha': 'Al-Baha',
    'region.najran': 'Najran',
    'region.riyadh': 'Riyadh',
    'region.qaseem': 'Qaseem',
    'region.hail': 'Hail',
    'region.jazan': 'Jazan',
    'region.tabuk': 'Tabuk',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.catalog': 'كتالوج البيانات',
    'nav.genomics': 'مركز الجينوم',
    'nav.research': 'الأبحاث والمجتمع',
    'nav.contact': 'اتصل بنا',
    'nav.submit': 'إرسال بيانات',
    'nav.centers': 'محطات البذور',
    'nav.inventory': 'بنك البذور',
    'nav.aiPrediction': 'التنبؤ بالذكاء الاصطناعي',
    'nav.publicAccess': 'وصول عام',

    // Header
    'header.title': 'مركز بيانات البذور',
    'header.subtitle': 'وزارة البيئة والمياه والزراعة',

    // Home Page
    'home.hero.title': 'مركز بيانات البذور والتقاوي - وزارة الزراعة',
    'home.hero.description': 'بيانات الجواز لـ 8 محاصيل (قمح، بن، شعير، دخن، ذرة رفيعة، سمسم، فول، مانجو) عبر تسع مناطق سعودية.',
    'home.hero.subtitle': 'وزارة البيئة والمياه والزراعة',
    'home.stats.total': 'إجمالي العينات',
    'home.stats.totalDesc': 'عبر جميع المناطق',
    'home.stats.wheat': 'انضمامات القمح',
    'home.stats.wheatDesc': 'أنواع القمح',
    'home.stats.coffee': 'انضمامات البن',
    'home.stats.coffeeDesc': 'البن العربي',
    'home.map.title': 'التوزيع الإقليمي',
    'home.map.description': 'خريطة تفاعلية توضح مواقع جمع البذور في المملكة العربية السعودية',
    'home.catalog.title': 'كتالوج البيانات',
    'home.catalog.description': 'تصفح قاعدة بيانات جواز السفر الكاملة للبذور',

    // Home badges & labels
    'home.badge.totalAccessions': 'إجمالي الاعتمادات',
    'home.badge.cropsWithData': 'محاصيل بيانات الجواز',
    'home.badge.saudiRegions': 'منطقة سعودية',
    'home.label.accessions': 'اعتماد',
    'home.label.activeRegions': 'مناطق نشطة',
    'home.label.saudiAccessions': 'اعتماد سعودي',
    'home.label.filteringBy': 'تصفية حسب:',
    'home.label.clearAll': 'مسح الكل',
    'home.label.showingSaudi': 'عرض {n} اعتماد سعودي',
    'home.label.clickRegion': 'انقر على علامة منطقة لتمييزها. انقر على بلاطات المحاصيل للتصفية.',
    'home.label.domCropColor': '(لون العلامة = المحصول السائد في المنطقة)',
    'home.label.passportSummary': 'ملخص بيانات الجواز',
    'home.label.clickToExplore': 'انقر على منطقة في الخريطة أو بلاطة محصول للاستكشاف',
    'home.label.totalAccessions': 'إجمالي الاعتمادات',
    'home.label.saudiCount': 'سعودي',
    'home.label.noteMappedRegions': 'اعتمادات سعودية من هذه المنطقة ببيانات الجواز. الاعتمادات الدولية (CIMMYT، ICARDA، إلخ) غير مُعروضة جغرافياً.',
    'home.label.regionBreakdown': 'توزيع المناطق',
    'home.kpi.totalAccessions': 'إجمالي الاعتمادات',
    'home.kpi.cropsTracked': 'محاصيل مُتتبعة',
    'home.kpi.saudiRegions': 'مناطق سعودية',
    'home.kpi.genomicData': 'بيانات جينومية',
    'home.kpi.tbData': 'تيرابايت',
    'home.chart.cropDistribution': 'توزيع المحاصيل',
    'home.chart.cropDistributionDesc': 'الاعتمادات حسب نوع المحصول',
    'home.chart.regionalOverview': 'نظرة إقليمية',
    'home.chart.regionalOverviewDesc': 'الاعتمادات السعودية لكل منطقة',
    'home.chart.sequencingBreakdown': 'تغطية التسلسل',
    'home.chart.sequencingDesc': 'GBS مقابل WGS عبر المحاصيل',
    'home.chart.saudiVsIntl': 'سعودي مقابل دولي',
    'home.chart.saudiVsIntlDesc': 'توزيع المنشأ لكل محصول',
    'home.section.exploreData': 'استكشف البيانات',
    'home.section.exploreDataDesc': 'رؤية شاملة لتوزيع البيانات الجينومية وجوازات البذور عبر المملكة العربية السعودية',
    'home.label.saudi': 'سعودي',
    'home.label.international': 'دولي',
    'home.label.gbs': 'GBS',
    'home.label.wgs': 'WGS',

    // Submit Data Page
    'submit.tab': 'إرسال البيانات',
    'submit.badge.new': 'بوابة إرسال البيانات',
    'submit.hero.title': 'إرسال البيانات الجينومية وبيانات الجواز',
    'submit.hero.description': 'ارفع بيانات التسلسل وسجلات جواز البذور. احصل على معرّف DOI من DataCite لمجموعة بياناتك للاستشهاد بها في المنشورات.',
    'submit.step.researcher.title': 'معلومات الباحث',
    'submit.step.researcher.desc': 'أخبرنا عن نفسك ومؤسستك',
    'submit.step.passport.title': 'بيانات جواز البذور',
    'submit.step.passport.desc': 'أدخل تفاصيل الاعتماد والجمع',
    'submit.step.genomic.title': 'البيانات الجينومية',
    'submit.step.genomic.desc': 'صف بيانات التسلسل وارفع الملفات',
    'submit.step.doi.title': 'تعيين DOI',
    'submit.step.doi.desc': 'راجع معرّف DOI والبيانات الوصفية',
    'submit.step.confirm.title': 'التأكيد',
    'submit.step.confirm.desc': 'تم إرسال بياناتك بنجاح',
    'submit.field.fullName': 'الاسم الكامل',
    'submit.field.institution': 'المؤسسة',
    'submit.field.department': 'القسم',
    'submit.field.email': 'البريد الإلكتروني',
    'submit.field.orcid': 'معرّف ORCID',
    'submit.hint.orcid': 'معرّف ORCID الخاص بك (اختياري)',
    'submit.field.crop': 'نوع المحصول',
    'submit.field.accessionId': 'رقم الاعتماد',
    'submit.field.region': 'منطقة الجمع',
    'submit.field.collectionDate': 'تاريخ الجمع',
    'submit.field.collectorName': 'اسم الجامع',
    'submit.field.siteDescription': 'وصف الموقع',
    'submit.field.latitude': 'خط العرض',
    'submit.field.longitude': 'خط الطول',
    'submit.field.altitude': 'الارتفاع',
    'submit.placeholder.selectCrop': 'اختر محصولاً...',
    'submit.placeholder.selectRegion': 'اختر منطقة...',
    'submit.field.sequencingType': 'نوع التسلسل',
    'submit.field.platform': 'منصة التسلسل',
    'submit.field.coverageDepth': 'عمق التغطية',
    'submit.field.fileTypes': 'أنواع الملفات',
    'submit.hint.fileTypes': 'حدد جميع أنواع الملفات المتضمنة في إرسالك',
    'submit.field.uploadFiles': 'رفع الملفات',
    'submit.upload.dragDrop': 'اسحب وأفلت الملفات هنا، أو انقر للتصفح',
    'submit.upload.maxSize': 'الحد الأقصى 50 جيجابايت لكل إرسال. يدعم FASTQ, BAM, VCF, PLINK.',
    'submit.field.sraAccession': 'رقم SRA/ENA (إن وُجد)',
    'submit.field.dataDescription': 'وصف مجموعة البيانات',
    'submit.placeholder.selectPlatform': 'اختر منصة التسلسل...',
    'submit.doi.title': 'معرّف DOI الخاص بك',
    'submit.doi.description': 'تم تعيين معرّف رقمي فريد لمجموعة بياناتك',
    'submit.doi.copyLink': 'نسخ رابط DOI',
    'submit.doi.copied': 'تم النسخ!',
    'submit.doi.resolvesTo': 'يُحال إلى:',
    'submit.doi.metadataPreview': 'بيانات DataCite الوصفية',
    'submit.confirm.title': 'تم الإرسال بنجاح!',
    'submit.confirm.description': 'تم إرسال بياناتك الجينومية وسجلات الجواز للمراجعة. ستتلقى بريدًا إلكترونيًا للتأكيد بمجرد نشر مجموعة بياناتك.',
    'submit.confirm.reviewNote': 'تتم مراجعة الإرسالات عادةً خلال 3-5 أيام عمل.',
    'submit.nav.back': 'رجوع',
    'submit.nav.next': 'متابعة',
    'submit.nav.mintDoi': 'إصدار DOI وإرسال',
    'submit.nav.submitAnother': 'إرسال مجموعة بيانات أخرى',

    // Data Catalog
    'catalog.title': 'كتالوج البيانات',
    'catalog.description': 'تصفح وابحث وصدّر بيانات جواز السفر الشاملة للبذور من مجموعات وزارة البيئة والمياه والزراعة',
    'catalog.totalRecords': 'إجمالي السجلات',
    'catalog.allAccessions': 'جميع الانضمامات',
    'catalog.wheat': 'القمح',
    'catalog.triticum': 'انضمامات القمح',
    'catalog.coffee': 'البن',
    'catalog.coffea': 'انضمامات البن',
    'catalog.exportData': 'تصدير البيانات',
    'catalog.fingerprints': 'قاعدة بيانات البصمات الوراثية',
    'catalog.fingerprintsDesc': 'الوصول إلى المؤشرات الجزيئية والرموز الشريطية للحمض النووي والبصمات الوراثية لجميع الانضمامات',
    'catalog.viewFingerprints': 'عرض البصمات',
    'catalog.filters': 'الفلاتر',
    'catalog.search': 'بحث',
    'catalog.searchPlaceholder': 'رقم الانضمام، الموقع...',
    'catalog.cropType': 'نوع المحصول',
    'catalog.regions': 'المناطق السعودية',
    'catalog.showing': 'عرض',
    'catalog.of': 'من',
    'catalog.samples': 'عينة',
    'catalog.exportCSV': 'تصدير CSV',
    'catalog.accessionId': 'رقم الانضمام',
    'catalog.crop': 'المحصول',
    'catalog.arabicName': 'الاسم العربي',
    'catalog.scientificName': 'الاسم العلمي',
    'catalog.country': 'الدولة',
    'catalog.region': 'المنطقة',
    'catalog.location': 'الموقع',

    // Genetic Fingerprints
    'fingerprints.title': 'البصمات الوراثية',
    'fingerprints.description': 'ملفات تعريف المؤشرات الجزيئية الشاملة والرموز الشريطية للحمض النووي لجميع انضمامات بذور وزارة البيئة والمياه والزراعة',
    'fingerprints.totalFingerprints': 'إجمالي البصمات',
    'fingerprints.completeProfiles': 'ملفات تعريف كاملة',
    'fingerprints.ssrMarkers': 'مؤشرات SSR',
    'fingerprints.acrossAccessions': 'عبر جميع الانضمامات',
    'fingerprints.dnaBarcodes': 'الرموز الشريطية للحمض النووي',
    'fingerprints.uniqueIdentifiers': 'معرفات فريدة',
    'fingerprints.genotypedLoci': 'المواقع الجينية المحددة',
    'fingerprints.perAccession': 'لكل انضمام',
    'fingerprints.searchTitle': 'البحث في البصمات الوراثية',
    'fingerprints.searchDesc': 'ابحث عن ملفات تعريف المؤشرات الجزيئية حسب رقم الانضمام أو الاسم المحلي',
    'fingerprints.searchPlaceholder': 'البحث برقم الانضمام أو الاسم...',
    'fingerprints.all': 'الكل',
    'fingerprints.database': 'قاعدة بيانات البصمات',
    'fingerprints.accessions': 'انضمام',
    'fingerprints.export': 'تصدير',
    'fingerprints.dnaBarcode': 'الرمز الشريطي للحمض النووي',
    'fingerprints.ssrProfile': 'ملف تعريف SSR',
    'fingerprints.geneticBarcode': 'الرمز الشريطي الوراثي',
    'fingerprints.ssrMarkerProfile': 'ملف تعريف مؤشر SSR',
    'fingerprints.showingOf': 'عرض',
    'fingerprints.loadMore': 'تحميل المزيد',
    'fingerprints.noResults': 'لم يتم العثور على بصمات',
    'fingerprints.noResultsDesc': 'حاول تعديل معايير البحث أو الفلاتر',

    // Genomics Hub
    'genomics.title': 'مركز الجينوم',
    'genomics.description': 'الوصول إلى التسلسلات الجينية والمؤشرات الجزيئية وأدوات المعلوماتية الحيوية',

    // Seed Stations (merged Centers + Exchange)
    'st.hero.badge': 'محطات البذور والتبادل',
    'st.hero.title': 'محطات البذور عبر المملكة',
    'st.hero.subtitle': 'استكشف محطات البذور، واطلب عينات الأصول الوراثية، وتابع طلبات تبادل البذور — في مكان واحد',
    'st.kpi.stations': 'المحطات',
    'st.kpi.staff': 'الموظفون',
    'st.kpi.experiments': 'التجارب',
    'st.kpi.distributed': 'كجم موزعة',
    'st.tab.map': 'عرض الخريطة',
    'st.tab.list': 'عرض القائمة',
    'st.tab.charts': 'مخططات المحطات',
    'st.tab.seeds': 'البذور المتاحة',
    'st.tab.process': 'عملية الطلب',
    'st.tab.guidelines': 'الإرشادات',
    'st.filter.region': 'المنطقة',
    'st.filter.allRegions': 'جميع المناطق',
    'st.filter.crop': 'المحصول',
    'st.filter.allCrops': 'جميع المحاصيل',
    'st.list.staff': 'موظف',
    'st.list.experiments': 'تجارب',
    'st.list.hortVarieties': 'أصناف بستانية',
    'st.seeds.requestTitle': 'طلب بذور',
    'st.seeds.requestDesc': 'تقديم طلب بذور جديد للبحث',
    'st.seeds.newRequest': 'طلب جديد',
    'st.seeds.browseTitle': 'تصفح الكتالوج',
    'st.seeds.browseDesc': 'استكشف عينات البذور المتاحة',
    'st.seeds.viewCatalog': 'عرض الكتالوج',
    'st.seeds.trackTitle': 'تتبع الطلبات',
    'st.seeds.trackDesc': 'متابعة حالة طلباتك',
    'st.seeds.myRequests': 'طلباتي',
    'st.seeds.featuredTitle': 'مجموعات البذور المميزة',
    'st.seeds.featuredDesc': 'عينات عالية الطلب متاحة للطلب الفوري',
    'st.seeds.available': 'متاح',
    'st.seeds.limited': 'محدود',
    'st.seeds.accession': 'رقم العينة',
    'st.seeds.qty': 'الكمية المتاحة',
    'st.seeds.requestSample': 'طلب عينة',
    'st.process.workflowTitle': 'سير عمل طلب البذور',
    'st.process.workflowDesc': 'عملية خطوة بخطوة لطلب عينات البذور من مركز بذور الوزارة',
    'st.process.step': 'الخطوة',
    'st.process.current': 'الحالية',
    'st.step1.title': 'تقديم الطلب',
    'st.step1.desc': 'إكمال نموذج الطلب عبر الإنترنت مع تفاصيل البحث والعينات المطلوبة',
    'st.step2.title': 'المراجعة والموافقة',
    'st.step2.desc': 'يراجع فريق الوزارة طلبك ومبررات البحث (2-5 أيام عمل)',
    'st.step3.title': 'اتفاقية نقل المواد',
    'st.step3.desc': 'توقيع اتفاقية نقل المواد التي تحدد شروط الاستخدام ومشاركة البيانات',
    'st.step4.title': 'تحضير البذور',
    'st.step4.desc': 'يتم تحضير البذور وتعبئتها وفحص جودتها للشحن',
    'st.step5.title': 'الشحن',
    'st.step5.desc': 'يتم شحن البذور إلى مؤسستك مع معلومات التتبع',
    'st.process.statusTitle': 'حالة طلبات العينات',
    'st.process.statusDesc': 'تتبع طلبات البذور الأخيرة',
    'st.process.viewDetails': 'عرض التفاصيل',
    'st.guide.eligTitle': 'متطلبات الأهلية',
    'st.guide.elig1': 'المؤسسات البحثية: الجامعات ومراكز البحث والجهات الحكومية التي تجري أبحاثاً زراعية',
    'st.guide.elig2': 'برامج التربية: منظمات تربية النباتات المسجلة ذات البرامج الموثقة',
    'st.guide.elig3': 'مشاريع الحفظ: مبادرات الحفظ والتنوع البيولوجي المعتمدة',
    'st.guide.elig4': 'الاستخدام التعليمي: المؤسسات الأكاديمية للتدريس ومشاريع بحث الطلاب',
    'st.guide.docsTitle': 'الوثائق المطلوبة',
    'st.guide.doc1': 'مقترح البحث: وصف تفصيلي لأهداف البحث والمنهجية',
    'st.guide.doc2': 'خطاب المؤسسة: خطاب رسمي من مؤسستك يدعم الطلب',
    'st.guide.doc3': 'توقيع اتفاقية نقل المواد: اتفاقية موقعة تقر بالشروط والأحكام',
    'st.guide.doc4': 'تصاريح الاستيراد: الشهادات الصحية النباتية المطلوبة للطلبات الدولية',
    'st.guide.termsTitle': 'شروط الاستخدام',
    'st.guide.termsIntro': 'البذور المقدمة من مركز بذور الوزارة للأغراض البحثية والتربية فقط. يجب على المستلمين:',
    'st.guide.term1': 'استخدام البذور فقط لأهداف البحث المحددة',
    'st.guide.term2': 'عدم توزيع البذور لأطراف ثالثة دون إذن',
    'st.guide.term3': 'ذكر الوزارة في المنشورات التي تستخدم الأصول الوراثية',
    'st.guide.term4': 'مشاركة نتائج البحث والبيانات وفقاً لاتفاقية نقل المواد',
    'st.guide.term5': 'الامتثال لبروتوكول ناغويا واللوائح الوطنية',
    'st.guide.contactTitle': 'معلومات الاتصال',
    'st.guide.coordinator': 'منسق تبادل البذور',
    'st.guide.email': 'البريد الإلكتروني',
    'st.guide.phone': 'الهاتف',
    'st.guide.hours': 'ساعات العمل',
    'st.guide.hoursVal': 'الأحد - الخميس، 8:00 صباحاً - 4:00 مساءً',
    'st.dialog.area': 'المساحة',
    'st.dialog.totalArea': 'المساحة الإجمالية',
    'st.dialog.utilizedArea': 'المساحة المستغلة',
    'st.dialog.staff': 'الكادر',
    'st.dialog.equipment': 'المعدات',
    'st.dialog.needs': 'الاحتياجات',
    'st.dialog.visits': 'الزيارات',
    'st.dialog.manager': 'مدير المحطة',
    'st.dialog.noContact': 'لا تتوفر بيانات اتصال',
    'st.dialog.crops': 'المحاصيل',
    'st.dialog.est': 'التأسيس',
    'st.dialog.experiments': 'تجارب زراعية',
    'st.dialog.cropsPlanted': 'المحاصيل المزروعة',
    'st.dialog.varieties': 'أصناف',
    'st.dialog.activities': 'الأنشطة',
    'st.dialog.seedExchange': 'تبادل البذور',
    'st.dialog.distYear': 'كجم موزعة/سنة',
    'st.dialog.recYear': 'كجم مستلمة/سنة',
    'st.dialog.partners': 'الشركاء',
    'st.dialog.contact': 'معلومات الاتصال',

    // Research & Community (merged)
    'research.title': 'الأبحاث والمجتمع العلمي',
    'research.description': 'المنشورات والمشاريع والباحثين والمؤسسات',
    'rc.hero.badge': 'مركز الأبحاث والمجتمع العلمي',
    'rc.hero.title': 'البحث الزراعي السعودي والمجتمع العلمي',
    'rc.hero.subtitle': '22 دراسة شاملة (2009–2025)، 127 باحثاً، و42 مؤسسة شريكة تعمل على تطوير الجينوم المحصولي في المملكة',
    'rc.kpi.studies': 'الدراسات',
    'rc.kpi.studiesSub': '2009–2025',
    'rc.kpi.researchers': 'الباحثون',
    'rc.kpi.researchersSub': 'أعضاء نشطون',
    'rc.kpi.institutions': 'المؤسسات',
    'rc.kpi.institutionsSub': 'منظمات شريكة',
    'rc.kpi.countries': 'الدول',
    'rc.kpi.countriesSub': 'انتشار عالمي',
    'rc.kpi.collaborations': 'التعاونات',
    'rc.kpi.collaborationsSub': 'مشاريع مشتركة',
    'rc.kpi.markers': 'أنواع الواسمات',
    'rc.kpi.markersSub': 'ISSR، SSR، SCoT، CRISPR…',
    'rc.tab.saudi': 'دراسات سعودية',
    'rc.tab.regional': 'إقليمية',
    'rc.tab.drought': 'دراسات الجفاف',
    'rc.tab.vegetables': 'الخضروات',
    'rc.tab.gaps': 'الفجوات والتوصيات',
    'rc.tab.seedcenter': 'أبحاث المركز',
    'rc.tab.researchers': 'الباحثون',
    'rc.tab.institutions': 'المؤسسات',
    'rc.markers': 'الواسمات',
    'rc.saudi.heading': 'الدراسات السعودية المباشرة الرئيسية',
    'rc.saudi.sub': '4 دراسات أُجريت مباشرة في المملكة العربية السعودية',
    'rc.regional.heading': 'الدراسات الإقليمية المطبقة على المملكة',
    'rc.regional.sub': '7 دراسات من منطقة الشرق الأوسط وشمال أفريقيا ذات صلة مباشرة',
    'rc.drought.heading': 'دراسات تحمل الجفاف في القمح والإجهاد',
    'rc.drought.sub': '5 دراسات — أنواع واسمات متعددة، تطبيقات سعودية مباشرة',
    'rc.drought.markerTitle': 'الواسمات الجزيئية الأكثر استخداماً',
    'rc.veg.heading': 'دراسات الخضروات والأصناف المحلية السعودية',
    'rc.veg.sub': '3 دراسات — حفظ التنوع الوراثي والتربية',
    'rc.seed.heading': 'دراسات الأمن الغذائي وبنوك البذور',
    'rc.seed.sub': '3 دراسات — حفظ البذور والأمن الغذائي في المناطق الجافة',
    'rc.gaps.gapsTitle': 'الفجوات البحثية في الزراعة السعودية',
    'rc.gaps.partnersTitle': 'المؤسسات الشريكة',
    'rc.gaps.recsTitle': 'توصيات لعلم الجينوم الزراعي السعودي',
    'rc.researchers.heading': 'الباحثون المميزون',
    'rc.researchers.sub': 'علماء ومربون يعملون مع موارد الأصول الوراثية لوزارة البيئة',
    'rc.researchers.contact': 'تواصل',
    'rc.researchers.expertise': 'التخصص البحثي',
    'rc.researchers.projects': 'المشاريع',
    'rc.researchers.publications': 'المنشورات',
    'rc.institutions.heading': 'المؤسسات الشريكة',
    'rc.institutions.sub': 'الجامعات ومنظمات البحث المتعاونة مع الوزارة',
    'rc.institutions.researchers': 'باحثون',
    'rc.institutions.projects': 'مشاريع',

    // Contact
    'contact.title': 'اتصل بنا',
    'contact.description': 'تواصل مع مركز بذور وزارة البيئة والمياه والزراعة',

    // About
    'about.title': 'عن مركز بذور وزارة البيئة والمياه والزراعة',
    'about.description': 'مهمتنا ورؤيتنا',

    // Footer
    'footer.title': 'مركز البذور - وزارة البيئة',
    'footer.subtitle': 'وزارة البيئة والمياه والزراعة',
    'footer.country': 'المملكة العربية السعودية',
    'footer.quickLinks': 'روابط سريعة',
    'footer.contact': 'اتصل بنا',
    'footer.email': 'البريد الإلكتروني: nalsofuani@mewa.gov.sa',
    'footer.phone': 'الهاتف: +966 50 018 3515',
    'footer.contactForm': 'نموذج الاتصال',
    'footer.rights': '© 2026 وزارة البيئة والمياه والزراعة. جميع الحقوق محفوظة.',

    // Common
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.cancel': 'إلغاء',
    'common.submit': 'إرسال',
    'common.close': 'إغلاق',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.download': 'تحميل',
    'common.upload': 'رفع',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.reset': 'إعادة تعيين',
    'common.apply': 'تطبيق',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.first': 'الأول',
    'common.last': 'الأخير',
    'common.page': 'صفحة',
    'common.perPage': 'لكل صفحة',
    'common.total': 'المجموع',
    'common.selected': 'محدد',
    'common.all': 'الكل',
    'common.none': 'لا شيء',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.crops': 'المحاصيل',
    'common.staff': 'الموظفون',
    'common.employees': 'موظف',
    'common.centers': 'مركز',
    'common.viewDetails': 'عرض التفاصيل',

    // Regions
    'region.taif': 'الطائف',
    'region.aseer': 'عسير',
    'region.albaha': 'الباحة',
    'region.najran': 'نجران',
    'region.riyadh': 'الرياض',
    'region.qaseem': 'القصيم',
    'region.hail': 'حائل',
    'region.jazan': 'جازان',
    'region.tabuk': 'تبوك',
  },
};
